# Generated by Django 4.2.5 on 2023-10-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="count_fcg",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="count_transit",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="count_uk_dispatch",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="count_uk_inward",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
