# Generated by Django 4.2.5 on 2023-10-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackapp", "0002_item_count_fcg_item_count_transit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="moq",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
