# Generated by Django 4.2.5 on 2023-10-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackapp", "0003_item_moq"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="moq_mail_flag",
            field=models.BooleanField(default=True),
        ),
    ]
