# Generated by Django 4.2.5 on 2023-10-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackapp", "0004_item_moq_mail_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="invoice_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
