# Generated by Django 4.2.5 on 2023-10-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trackapp",
            "0005_transaction_invoice_date_transaction_invoice_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="state",
            field=models.CharField(
                choices=[
                    ("FG", "Finished Goods"),
                    ("EXPORT_INDIA", "Export India"),
                    ("UK_INWARDS", "UK Inwards"),
                    ("UK_DISPATCH", "UK Dispatch"),
                ],
                default="FG",
                max_length=15,
            ),
        ),
    ]
