# Generated by Django 4.2.5 on 2023-10-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackapp", "0006_qrcode_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="value",
            field=models.TextField(default=""),
        ),
    ]
