# Generated by Django 4.2.5 on 2023-12-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackapp", "0007_alter_transaction_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="count_uk_dispatch",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="item",
            name="count_uk_inward",
            field=models.FloatField(default=0),
        ),
    ]
